language: node_js
node_js:
- '8'
cache: yarn
script: yarn test
before_deploy: yarn build
deploy:
  provider: firebase
  project: drop-app-production
  skip_cleanup: true
  token:
    secure: E2V13uI5xx+eGbJdCr93OWP/BHZMAY+ga5dliK0+6XfYpl8EVsYSXIXkfB0W+WimQCYLjaksqS309edjkTyW52qLHsx4rmPEVjXITp+4rXXItWWh+twyRWz9/Z5KA15bv/VAnlFiS91EbZnsj1YIm0iXoaMDTtj5mzwuRe/wy+0cv492lQbXhCqoWmEqxWVNJqWG1fODLAGW7wVqY6f2dLcX4K/RxHjNXIpW3yc9Zua756JuBLSffcPUvzqYnGlGcgnnF6Rlz523ZjKy0XKJxq0mWW47JtVdFfh6UQxE4NM6OP8B11ihZ5B3kQOJ+LGl9xUEAo52rPJyB6zGsyEg6nUGGDmF9F9zVOXIpnyIDV6e5fHNrfAu9m+WRB/wjN2A4eGHxBes+IJdJ8vVcHRD8h3EDS2n7HNWx22fu4oD5KF2aqqv5pelyJiIbWniCSOAkNG7o0EonX+t3dz8RU3hXOR3OwMLCQFch3WJE66JE20CpTzSmoEiZHg8e29d9n1QXWJjOQHzswBDInxJZec42tdj3Go/9PYXuG5n51tLk06jX911mSXh2v8OqfL3OqkUq0rd94HBDMfo26a8rngiCz+/ZlQStr03r4awx9pxQtrDkDdZHlbfBsGkhLOKzBrJk2Fg082vNXLfXpD/FoAlhusQEU2XMmq1IOiqb8QR+ns=
notifications:
  slack:
    secure: HdnPkrlDv7x1LQaI68Bt1MGLbwl2qnwFtoPiqLcI+8nIlBsFcnYppukLWjBSLqPPNLQmLR3pPur/kV9wwxUnuyhCAE1J3+M+4GDcAWJRGDq60eyv7FP4C5CL7PGtFA70TLeIEEl+PoVUwQ+hwVz2YmJajYJ0PmBqqaT+oEduvCyTl/PNThicqZAVnt10lQQkrAD4fipM1grzC35GP/tsEjxU/W/EDR5I8eDPRkypiQbIWD0YwsdK9iwDnZXaua9QE3C8H46m/UwIzSGJBPkk5v7P8HM2X33ZfoBWMJ3mj/uOAn2F7Jd9IUIel69lxZxeK8jwuVjV6pudp/iaxW/FGcyeAqeLiE071L1QcwPykxdKDDbCdvD7SsZRduPIMOjwtHDkocW1GMLDGa1g44IoyPBV+4UO+CqBa/8JKMlndahkdrpouUiraxEZrYWmHoHrifaFwRVmOjICG9B3ylKOFBMUGexT/gE/9xqpbSXN0QBPzkSFnfDHCcEiib6MCTZECqgZpi3LS+lRJk06qB2pCDWHA5gC2xnfoix2DEMN7Bs2cHW5BAR6LRYmPO+Oig+J43B2cFV24Oyy23E71jnYuV1ujpM/HJ/r9YlfaCW95XYWtr8BvWyO2CsUPWtKFxBOh0077JNyGF6hsEeMm39kVbSv6o6GQBfLiBmE640qO6I=
